<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>טיפול שורש בדיקות אוטומטיות assert None</title>
    <link>https://forums.pythonic.guru/t/assert-none/6742</link>
    <description>![image|690x100](upload://sfrw5jn2VfHhZzgnrnkkzYXzQWL.png) 

הכל רץ גם עם הערך שהתקבל הוא None, למרות זאת הבוקר האוטומטי ממשיך להציג שגיאה כזו.
רעיונות?</description>
    <language>he</language>
    <lastBuildDate>Thu, 28 May 2020 09:02:07 +0000</lastBuildDate>
    <category>שבוע 6</category>
    <atom:link href="https://forums.pythonic.guru/t/assert-none/6742.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>טיפול שורש בדיקות אוטומטיות assert None</title>
        <dc:creator><![CDATA[aviadamar]]></dc:creator>
        <description><![CDATA[
            <p>שם הפונקציה שלך … תשנה אותה למה שרשום בהערה.</p>
          <p><a href="https://forums.pythonic.guru/t/assert-none/6742/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/assert-none/6742/2</link>
        <pubDate>Thu, 28 May 2020 09:02:07 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-6742-2</guid>
        <source url="https://forums.pythonic.guru/t/assert-none/6742.rss">טיפול שורש בדיקות אוטומטיות assert None</source>
      </item>
      <item>
        <title>טיפול שורש בדיקות אוטומטיות assert None</title>
        <dc:creator><![CDATA[arieveksler]]></dc:creator>
        <description><![CDATA[
            <p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/c/c5fbca07c5e6fec4cb58c8e396805d2cbc2e9fe3.png" data-download-href="https://forums.pythonic.guru/uploads/default/c5fbca07c5e6fec4cb58c8e396805d2cbc2e9fe3" title="image"><img src="https://forums.pythonic.guru/uploads/default/optimized/2X/c/c5fbca07c5e6fec4cb58c8e396805d2cbc2e9fe3_2_690x100.png" alt="image" data-base62-sha1="sfrw5jn2VfHhZzgnrnkkzYXzQWL" width="690" height="100" srcset="https://forums.pythonic.guru/uploads/default/optimized/2X/c/c5fbca07c5e6fec4cb58c8e396805d2cbc2e9fe3_2_690x100.png, https://forums.pythonic.guru/uploads/default/optimized/2X/c/c5fbca07c5e6fec4cb58c8e396805d2cbc2e9fe3_2_1035x150.png 1.5x, https://forums.pythonic.guru/uploads/default/optimized/2X/c/c5fbca07c5e6fec4cb58c8e396805d2cbc2e9fe3_2_1380x200.png 2x" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/c/c5fbca07c5e6fec4cb58c8e396805d2cbc2e9fe3_2_10x10.png"></a></div><p></p>
<p>הכל רץ גם עם הערך שהתקבל הוא None, למרות זאת הבוקר האוטומטי ממשיך להציג שגיאה כזו.<br>
רעיונות?</p>
          <p><a href="https://forums.pythonic.guru/t/assert-none/6742/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/assert-none/6742/1</link>
        <pubDate>Thu, 28 May 2020 09:01:41 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-6742-1</guid>
        <source url="https://forums.pythonic.guru/t/assert-none/6742.rss">טיפול שורש בדיקות אוטומטיות assert None</source>
      </item>
  </channel>
</rss>
