<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
    <link>https://forums.pythonic.guru/t/pytest/9119</link>
    <description>![2021-02-17 (4)|690x127](upload://wOdgmgkTHlB9jrWxeGvpbCwtzl8.png) 
מופיעה לי השגיאה הזאת. אני מממשת את האובייקטים שלי בקובץ calendar.py
ובבדיקה בDB BROWSER רואה שכן קיימת הטבלה שעשיתי(וכמובן שהפיצר מוצג באתר)
אפשר עזרה במציאת פתרון? די אובדת עצות</description>
    <language>he</language>
    <lastBuildDate>Thu, 18 Feb 2021 18:40:18 +0000</lastBuildDate>
    <category>עזרה ושיתופי פעולה</category>
    <atom:link href="https://forums.pythonic.guru/t/pytest/9119.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[elor550]]></dc:creator>
        <description><![CDATA[
            <p>מצאת את הבעיה? <a class="mention" href="https://forums.pythonic.guru/u/yam">@Yam</a> <img src="https://forums.pythonic.guru/images/emoji/twitter/frowning.png?v=9" title=":frowning:" class="emoji" alt=":frowning:"></p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/12">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/12</link>
        <pubDate>Thu, 18 Feb 2021 18:40:18 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-12</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[elor550]]></dc:creator>
        <description><![CDATA[
            <p>בטח,</p><aside class="onebox githubpullrequest">
  <header class="source">
      <a href="https://github.com/PythonFreeCourse/calendar/pull/260" target="_blank" rel="noopener nofollow ugc">github.com/PythonFreeCourse/calendar</a>
  </header>
  <article class="onebox-body">
    <div class="github-row">
  <div class="github-icon-container" title="Pull Request">
    <svg width="60" height="60" class="github-icon" viewBox="0 0 12 16" aria-hidden="true"><path d="M11 11.28V5c-.03-.78-.34-1.47-.94-2.06C9.46 2.35 8.78 2.03 8 2H7V0L4 3l3 3V4h1c.27.02.48.11.69.31.21.2.3.42.31.69v6.28A1.993 1.993 0 0 0 10 15a1.993 1.993 0 0 0 1-3.72zm-1 2.92c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zM4 3c0-1.11-.89-2-2-2a1.993 1.993 0 0 0-1 3.72v6.56A1.993 1.993 0 0 0 2 15a1.993 1.993 0 0 0 1-3.72V4.72c.59-.34 1-.98 1-1.72zm-.8 10c0 .66-.55 1.2-1.2 1.2-.65 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2zM2 4.2C1.34 4.2.8 3.65.8 3c0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2z"></path></svg>
  </div>

  <div class="github-info-container">
    <h4>
      <a href="https://github.com/PythonFreeCourse/calendar/pull/260" target="_blank" rel="noopener nofollow ugc">Feature/parasha</a>
    </h4>

    <div class="branches">
      <code>PythonFreeCourse:develop</code> ← <code>elor555:feature/parasha</code>
    </div>

    <div class="github-info">
      <div class="date">
        opened <span class="discourse-local-date" data-format="ll" data-date="2021-02-11" data-time="16:56:26" data-timezone="UTC">04:56PM - 11 Feb 21 UTC</span>
      </div>

      <div class="user">
        <a href="https://github.com/elor555" target="_blank" rel="noopener nofollow ugc">
          <img alt="elor555" src="https://forums.pythonic.guru/uploads/default/original/2X/4/4d7007df5cacfd29b05e7a486f8ccfc90431987f.png" class="onebox-avatar-inline" width="20" height="20">
          elor555
        </a>
      </div>

      <div class="lines" title="50 commits changed 12 files with 444 additions and 60 deletions">
        <a href="https://github.com/PythonFreeCourse/calendar/pull/260/files" target="_blank" rel="noopener nofollow ugc">
          <span class="added">+444</span>
          <span class="removed">-60</span>
        </a>
      </div>
    </div>

  </div>
</div>

  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

          <p><a href="https://forums.pythonic.guru/t/pytest/9119/11">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/11</link>
        <pubDate>Thu, 18 Feb 2021 13:28:46 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-11</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>יש קישור ל־PR שאפשר להסתכל עליו?</p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/10">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/10</link>
        <pubDate>Thu, 18 Feb 2021 13:20:55 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-10</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[elor550]]></dc:creator>
        <description><![CDATA[
            <p>======================================================================================== FAILURES ========================================================================================<br>
___________________________________________________________________________ TestCalendarGrid.test_get_calendar ___________________________________________________________________________</p>
<p>client = &lt;starlette.testclient.TestClient object at 0x0000018ED660DA90&gt;</p>
<pre><code>@staticmethod
def test_get_calendar(client):
</code></pre>
<blockquote>
<pre><code>  response = client.get("/calendar/month")
</code></pre>
</blockquote>
<p>tests\test_calendar_grid.py:24:</p>
<hr>
<p>…\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py:555: in get<br>
return self.request(‘GET’, url, **kwargs)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\testclient.py:413: in request<br>
return super().request(<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py:542: in request<br>
resp = self.send(prep, **send_kwargs)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py:677: in send<br>
history = [resp for resp in gen]<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py:677: in <br>
history = [resp for resp in gen]<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py:237: in resolve_redirects<br>
resp = self.send(<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py:655: in send<br>
r = adapter.send(request, **kwargs)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\testclient.py:243: in send<br>
raise exc from None<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\testclient.py:240: in send<br>
loop.run_until_complete(self.app(scope, receive, send))<br>
…\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py:642: in run_until_complete<br>
return future.result()<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\applications.py:199: in <strong>call</strong><br>
await super().<strong>call</strong>(scope, receive, send)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\applications.py:111: in <strong>call</strong><br>
await self.middleware_stack(scope, receive, send)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py:181: in <strong>call</strong><br>
raise exc from None<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py:159: in <strong>call</strong><br>
await self.app(scope, receive, _send)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py:82: in <strong>call</strong><br>
raise exc from None<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py:71: in <strong>call</strong><br>
await self.app(scope, receive, sender)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py:566: in <strong>call</strong><br>
await route.handle(scope, receive, send)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py:227: in handle<br>
await self.app(scope, receive, send)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py:41: in app<br>
response = await func(request)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py:201: in app<br>
raw_response = await run_endpoint_function(<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py:148: in run_endpoint_function<br>
return await dependant.call(**values)<br>
app\routers\calendar.py:24: in calendar<br>
parasha_obj = weekly_parasha.get_all_parahot_list(session)<br>
app\internal\weekly_parasha.py:23: in get_all_parahot_list<br>
return session.query(Parasha).all()<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py:3373: in all<br>
return list(self)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py:3535: in <strong>iter</strong><br>
return self._execute_and_instances(context)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py:3560: in _execute_and_instances<br>
result = conn.execute(querycontext.statement, self._params)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py:1011: in execute<br>
return meth(self, multiparams, params)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py:298: in _execute_on_connection<br>
return connection._execute_clauseelement(self, multiparams, params)<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py:1124: in _execute_clauseelement<br>
ret = self._execute_context(<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py:1316: in _execute_context<br>
self.<em>handle_dbapi_exception(<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py:1510: in <em>handle_dbapi_exception<br>
util.raise</em>(<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py:182: in raise</em><br>
raise exception<br>
…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py:1276: in _execute_context<br>
self.dialect.do_execute(</p>
<hr>
<p>self = &lt;sqlalchemy.dialects.sqlite.pysqlite.SQLiteDialect_pysqlite object at 0x0000018ECCB11400&gt;, cursor = &lt;sqlite3.Cursor object at 0x0000018ED52841F0&gt;<br>
statement = ‘SELECT parashot.id AS parashot_id, parashot.name AS parashot_name, parashot.hebrew_name AS parashot_hebrew_name, parashot.link AS parashot_link, parashot.date AS parashot_dat<br>
e \nFROM parashot’<br>
parameters = (), context = &lt;sqlalchemy.dialects.sqlite.base.SQLiteExecutionContext object at 0x0000018ED6A9F100&gt;</p>
<pre><code>def do_execute(self, cursor, statement, parameters, context=None):
</code></pre>
<blockquote>
<pre><code>  cursor.execute(statement, parameters)
</code></pre>
</blockquote>
<p>E       sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: parashot<br>
E       [SQL: SELECT parashot.id AS parashot_id, parashot.name AS parashot_name, parashot.hebrew_name AS parashot_hebrew_name, parashot.link AS parashot_link, parashot.date AS parashot_da<br>
te<br>
E       FROM parashot]<br>
E       (Background on this error at: <a href="http://sqlalche.me/e/13/e3q8" rel="noopener nofollow ugc">http://sqlalche.me/e/13/e3q8</a>)</p>
<p>…\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py:609: OperationalError<br>
==================================================================================== warnings summary ====================================================================================<br>
tests/test_a_telegram_asyncio.py::TestBotClient::test_user_not_registered<br>
tests/test_a_telegram_asyncio.py::TestBotClient::test_user_registered<br>
tests/test_a_telegram_asyncio.py::TestHandlers::test_today_handler<br>
tests/test_a_telegram_asyncio.py::TestHandlers::test_chosen_day_handler<br>
tests/test_a_telegram_asyncio.py::TestHandlers::test_process_new_event<br>
tests/test_about.py::test_about_page<br>
C:\Users\אילור\AppData\Local\Programs\Python\Python39\lib\site-packages_pytest\unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: &lt;function _ProactorBas<br>
ePipeTransport.<strong>del</strong> at 0x0000018E88B0C4C0&gt;</p>
<p>Traceback (most recent call last):<br>
File “C:\Users\אילור\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py”, line 116, in <strong>del</strong><br>
self.close()<br>
File “C:\Users\אילור\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py”, line 108, in close<br>
self._loop.call_soon(self._call_connection_lost, None)<br>
File “C:\Users\אילור\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py”, line 746, in call_soon<br>
self._check_closed()<br>
File “C:\Users\אילור\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py”, line 510, in _check_closed<br>
raise RuntimeError(‘Event loop is closed’)<br>
RuntimeError: Event loop is closed</p>
<pre><code>warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
</code></pre>
<p>tests/test_comment.py::test_delete_comment<br>
tests/test_event.py::test_delete_comment<br>
C:\Users\אילור\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py:1359: SAWarning: DELETE statement on table ‘comments’ expected to delete 1 row(s);<br>
0 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.<br>
util.warn(</p>
<p>tests/test_export.py::TestExport::test_export<br>
C:\Users\אילור\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\concurrency.py:16: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is d<br>
eprecated since Python 3.8, and scheduled for removal in Python 3.11.<br>
(done, pending) = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)</p>
<p>tests/test_utils.py::TestUtils::test_delete_instance<br>
C:\Users\אילור\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py:1359: SAWarning: DELETE statement on table ‘users’ expected to delete 1 row(s); 0 w<br>
ere matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.<br>
util.warn(</p>
<p>– Docs: <a href="https://docs.pytest.org/en/stable/warnings.html" class="inline-onebox" rel="noopener nofollow ugc">Warnings Capture — pytest documentation</a><br>
================================================================================ short test summary info =================================================================================<br>
FAILED tests/test_calendar_grid.py::TestCalendarGrid::test_get_calendar - sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: parashot</p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/9">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/9</link>
        <pubDate>Thu, 18 Feb 2021 12:27:45 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-9</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>תוכלי להעתיק ולהדביק לפה את כל הלוג בבקשה?</p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/8">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/8</link>
        <pubDate>Thu, 18 Feb 2021 12:10:14 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-8</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[elor550]]></dc:creator>
        <description><![CDATA[
            <p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/4/46002f754d719ce69772bb3629403f147d04b464.png" data-download-href="https://forums.pythonic.guru/uploads/default/46002f754d719ce69772bb3629403f147d04b464" title="2021-02-18"><img src="https://forums.pythonic.guru/uploads/default/optimized/2X/4/46002f754d719ce69772bb3629403f147d04b464_2_690x388.png" alt="2021-02-18" data-base62-sha1="9ZfOQw8UfBhHn8Ov3esVp2lI9MM" width="690" height="388" srcset="https://forums.pythonic.guru/uploads/default/optimized/2X/4/46002f754d719ce69772bb3629403f147d04b464_2_690x388.png, https://forums.pythonic.guru/uploads/default/optimized/2X/4/46002f754d719ce69772bb3629403f147d04b464_2_1035x582.png 1.5x, https://forums.pythonic.guru/uploads/default/optimized/2X/4/46002f754d719ce69772bb3629403f147d04b464_2_1380x776.png 2x" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/4/46002f754d719ce69772bb3629403f147d04b464_2_10x10.png"></a></div><br>
זה מחזיר לי את זה<p></p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/7">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/7</link>
        <pubDate>Thu, 18 Feb 2021 11:25:57 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-7</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>הרי את מקבלת פלט של pytest שנכשל.<br>
אז במקום להריץ pytest כרגיל, הריצי אותו עם <code>-vvv</code></p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/6">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/6</link>
        <pubDate>Thu, 18 Feb 2021 10:58:21 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-6</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[elor550]]></dc:creator>
        <description><![CDATA[
            <aside class="quote no-group" data-username="Yam" data-post="4" data-topic="9119">
<div class="title">
<div class="quote-controls"></div>
<img alt="" width="20" height="20" src="https://forums.pythonic.guru/user_avatar/forums.pythonic.guru/yam/40/6_2.png" class="avatar"> Yam:</div>
<blockquote>
<p>pytest עם vvv-,</p>
</blockquote>
</aside>
<p>הכוונה לבדיקה הזאת:<br>
python -m pytest --cov-report term-missing --cov=app tests<br>
???</p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/5">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/5</link>
        <pubDate>Thu, 18 Feb 2021 10:57:43 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-5</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>נסי להריץ את pytest עם vvv-, זה יתן Traceback של איפה זה קרס</p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/4">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/4</link>
        <pubDate>Thu, 18 Feb 2021 10:55:03 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-4</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[elor550]]></dc:creator>
        <description><![CDATA[
            <p>לא אני יצרתי את הטסט,ולכן לא יודעת להצביע מה הבעיה.גם מי שכתב את הטסט הזה לא יודע להצביע</p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/3">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/3</link>
        <pubDate>Thu, 18 Feb 2021 10:54:05 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-3</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>איך נראים הטסטים? הסתכלת באיך אחרים מימשו את הטסטים שלהם? <img src="https://forums.pythonic.guru/images/emoji/twitter/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/2</link>
        <pubDate>Thu, 18 Feb 2021 10:28:49 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-2</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
      <item>
        <title>שגיאה בPYTEST-לא קיימת טבלה כזאת</title>
        <dc:creator><![CDATA[elor550]]></dc:creator>
        <description><![CDATA[
            <p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/e/e5f2ac1f7a9d6d9135937fc8075e9bdde0c24f42.png" data-download-href="https://forums.pythonic.guru/uploads/default/e5f2ac1f7a9d6d9135937fc8075e9bdde0c24f42" title="2021-02-17 (4)"><img src="https://forums.pythonic.guru/uploads/default/optimized/2X/e/e5f2ac1f7a9d6d9135937fc8075e9bdde0c24f42_2_690x127.png" alt="2021-02-17 (4)" data-base62-sha1="wOdgmgkTHlB9jrWxeGvpbCwtzl8" width="690" height="127" srcset="https://forums.pythonic.guru/uploads/default/optimized/2X/e/e5f2ac1f7a9d6d9135937fc8075e9bdde0c24f42_2_690x127.png, https://forums.pythonic.guru/uploads/default/optimized/2X/e/e5f2ac1f7a9d6d9135937fc8075e9bdde0c24f42_2_1035x190.png 1.5x, https://forums.pythonic.guru/uploads/default/optimized/2X/e/e5f2ac1f7a9d6d9135937fc8075e9bdde0c24f42_2_1380x254.png 2x" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/e/e5f2ac1f7a9d6d9135937fc8075e9bdde0c24f42_2_10x10.png"></a></div><br>
מופיעה לי השגיאה הזאת. אני מממשת את האובייקטים שלי בקובץ calendar.py<br>
ובבדיקה בDB BROWSER רואה שכן קיימת הטבלה שעשיתי(וכמובן שהפיצר מוצג באתר)<br>
אפשר עזרה במציאת פתרון? די אובדת עצות<p></p>
          <p><a href="https://forums.pythonic.guru/t/pytest/9119/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest/9119/1</link>
        <pubDate>Thu, 18 Feb 2021 10:16:55 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9119-1</guid>
        <source url="https://forums.pythonic.guru/t/pytest/9119.rss">שגיאה בPYTEST-לא קיימת טבלה כזאת</source>
      </item>
  </channel>
</rss>
