<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>ספיידר 3 לא עובד</title>
    <link>https://forums.pythonic.guru/t/topic/7117</link>
    <description>אחרי שעבדתי עם ספיידר, פתאום הוא יצא מהתוכנית, וכשניסיתי לפתוח קיבלתי את ההודעה הזאת:
![image|690x388](upload://i7c3Wxwju94elaFdB7JVgN1GU3L.png) 

עשיתי ריסטרט למחשב - לא עזר
מחקתי והתקנתי מחדש- לא עזר
עשיתי -
spyder reset -לא עזר
 conda update --all -לא עזר (ניסיתי גם דרך conda prompy)

האמת שרק אתמול הורדתי מהאינטרנט את ספיידר, אחרי שהתקנתי מחדש בגלל שספרייה מסויימת לא עבדה לי.

עריכה: כשאני עושה conda update --all, אני מקבל:
Preparing transaction: done
Verifying transaction: failed

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\Anaconda3

למישהו יש רעיון איך לפתור?</description>
    <language>he</language>
    <lastBuildDate>Fri, 12 Jun 2020 13:38:49 +0000</lastBuildDate>
    <category>מחוץ לקטגוריה</category>
    <atom:link href="https://forums.pythonic.guru/t/topic/7117.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>ספיידר 3 לא עובד</title>
        <dc:creator><![CDATA[krauskas]]></dc:creator>
        <description><![CDATA[
            <p>יש עכשיו זה עובד:slight_smile: <img src="https://forums.pythonic.guru/images/emoji/twitter/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
          <p><a href="https://forums.pythonic.guru/t/topic/7117/5">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/7117/5</link>
        <pubDate>Fri, 12 Jun 2020 13:38:49 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-7117-5</guid>
        <source url="https://forums.pythonic.guru/t/topic/7117.rss">ספיידר 3 לא עובד</source>
      </item>
      <item>
        <title>ספיידר 3 לא עובד</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <aside class="quote no-group" data-username="krauskas" data-post="1" data-topic="7117">
<div class="title">
<div class="quote-controls"></div>
<img alt="" width="20" height="20" src="https://forums.pythonic.guru/letter_avatar_proxy/v4/letter/k/bc8723/40.png" class="avatar"> krauskas:</div>
<blockquote>
<p>עריכה: כשאני עושה conda update --all, אני מקבל:<br>
Preparing transaction: done<br>
Verifying transaction: failed</p>
<p>EnvironmentNotWritableError: The current user does not have write permissions to the target environment.<br>
environment location: C:\ProgramData\Anaconda3</p>
</blockquote>
</aside>
<p>פתח את חלון ה¯cmd כ¯Administrator ונסה שוב</p>
          <p><a href="https://forums.pythonic.guru/t/topic/7117/4">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/7117/4</link>
        <pubDate>Fri, 12 Jun 2020 13:34:39 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-7117-4</guid>
        <source url="https://forums.pythonic.guru/t/topic/7117.rss">ספיידר 3 לא עובד</source>
      </item>
      <item>
        <title>ספיידר 3 לא עובד</title>
        <dc:creator><![CDATA[krauskas]]></dc:creator>
        <description><![CDATA[
            <aside class="quote no-group" data-username="Yam" data-post="2" data-topic="7117">
<div class="title">
<div class="quote-controls"></div>
<img alt="" width="20" height="20" src="https://forums.pythonic.guru/user_avatar/forums.pythonic.guru/yam/40/6_2.png" class="avatar"> Yam:</div>
<blockquote>
<p>spyder --reset</p>
</blockquote>
</aside>
<p>*** Reset Spyder settings to defaults ***<br>
removing: C:\Users\Hagai.spyder-py3\template.py<br>
removing: C:\Users\Hagai.spyder-py3\history_internal.py<br>
removing: C:\Users\Hagai.spyder-py3\workingdir<br>
removing: C:\Users\Hagai.spyder-py3\langconfig<br>
removing: C:\Users\Hagai.spyder-py3\spyder.lock<br>
removing: C:\Users\Hagai.spyder-py3\config\spyder.ini<br>
removing: C:\Users\Hagai.spyder-py3\config\transient.ini<br>
removing: C:\Users\Hagai.spyder-py3\plugins</p>
          <p><a href="https://forums.pythonic.guru/t/topic/7117/3">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/7117/3</link>
        <pubDate>Fri, 12 Jun 2020 13:32:35 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-7117-3</guid>
        <source url="https://forums.pythonic.guru/t/topic/7117.rss">ספיידר 3 לא עובד</source>
      </item>
      <item>
        <title>ספיידר 3 לא עובד</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>מה מדפיס לך <code>spyder --reset</code>?</p>
          <p><a href="https://forums.pythonic.guru/t/topic/7117/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/7117/2</link>
        <pubDate>Fri, 12 Jun 2020 13:26:37 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-7117-2</guid>
        <source url="https://forums.pythonic.guru/t/topic/7117.rss">ספיידר 3 לא עובד</source>
      </item>
      <item>
        <title>ספיידר 3 לא עובד</title>
        <dc:creator><![CDATA[krauskas]]></dc:creator>
        <description><![CDATA[
            <p>אחרי שעבדתי עם ספיידר, פתאום הוא יצא מהתוכנית, וכשניסיתי לפתוח קיבלתי את ההודעה הזאת:<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/7/7ef75482c9835a2991bf2fce7b75ab1ed762bee9.png" data-download-href="https://forums.pythonic.guru/uploads/default/7ef75482c9835a2991bf2fce7b75ab1ed762bee9" title="image"><img src="https://forums.pythonic.guru/uploads/default/optimized/2X/7/7ef75482c9835a2991bf2fce7b75ab1ed762bee9_2_690x388.png" alt="image" data-base62-sha1="i7c3Wxwju94elaFdB7JVgN1GU3L" width="690" height="388" srcset="https://forums.pythonic.guru/uploads/default/optimized/2X/7/7ef75482c9835a2991bf2fce7b75ab1ed762bee9_2_690x388.png, https://forums.pythonic.guru/uploads/default/optimized/2X/7/7ef75482c9835a2991bf2fce7b75ab1ed762bee9_2_1035x582.png 1.5x, https://forums.pythonic.guru/uploads/default/optimized/2X/7/7ef75482c9835a2991bf2fce7b75ab1ed762bee9_2_1380x776.png 2x" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/7/7ef75482c9835a2991bf2fce7b75ab1ed762bee9_2_10x10.png"></a></div><p></p>
<p>עשיתי ריסטרט למחשב - לא עזר<br>
מחקתי והתקנתי מחדש- לא עזר<br>
עשיתי -<br>
spyder reset -לא עזר<br>
conda update --all -לא עזר (ניסיתי גם דרך conda prompy)</p>
<p>האמת שרק אתמול הורדתי מהאינטרנט את ספיידר, אחרי שהתקנתי מחדש בגלל שספרייה מסויימת לא עבדה לי.</p>
<p>עריכה: כשאני עושה conda update --all, אני מקבל:<br>
Preparing transaction: done<br>
Verifying transaction: failed</p>
<p>EnvironmentNotWritableError: The current user does not have write permissions to the target environment.<br>
environment location: C:\ProgramData\Anaconda3</p>
<p>למישהו יש רעיון איך לפתור?</p>
          <p><a href="https://forums.pythonic.guru/t/topic/7117/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/7117/1</link>
        <pubDate>Fri, 12 Jun 2020 13:23:51 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-7117-1</guid>
        <source url="https://forums.pythonic.guru/t/topic/7117.rss">ספיידר 3 לא עובד</source>
      </item>
  </channel>
</rss>
