<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>פותחים שעון - פינלי</title>
    <link>https://forums.pythonic.guru/t/topic/7648</link>
    <description>היוש, שמתי return  בתוך הכשלבסוף בדיוק כמו בדוגמה שלפניו וקיבלתי את השגיאה הבאה מהבודק:

    הבודק האוטומטי: B012-return/continue/break inside finally blocks cause exceptions to be silenced. Exceptions should be silenced in except blocks. Control statements can be moved outside the finally bloc

האם הותעתי ע&quot;י התרגיל שלפניו?</description>
    <language>he</language>
    <lastBuildDate>Sun, 26 Jul 2020 10:48:42 +0000</lastBuildDate>
    <category>שבוע 8</category>
    <atom:link href="https://forums.pythonic.guru/t/topic/7648.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>פותחים שעון - פינלי</title>
        <dc:creator><![CDATA[elador9]]></dc:creator>
        <description><![CDATA[
            <p>דיברו על זה פה <img src="https://forums.pythonic.guru/images/emoji/twitter/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"> :<br>
</p><aside class="quote quote-modified" data-post="1" data-topic="7587">
  <div class="title">
    <div class="quote-controls"></div>
    <img alt="" width="20" height="20" src="/letter_avatar_proxy/v4/letter/n/ce73a5/40.png" class="avatar">
    <a href="https://forums.pythonic.guru/t/4-return-finally/7587">פותחים שעון - מחברת 4 - פקודת return בבלוק ה-finally</a> <a class="badge-wrapper  bullet" href="https://forums.pythonic.guru/c/week-8/18"><span class="badge-category-bg" style="background-color: #0088CC;"></span><span style="" data-drop-close="true" class="badge-category clear-badge" title="כאן תוכלו לשאול שאלות ולהתדיין על החומר של שבוע 8.">שבוע 8</span></a>
  </div>
  <blockquote>
    שמתי לב כי הבודק האוטומטי מעיר על ביצוע פקודת return בבלוק ה-finally, כמו בדוגמה שניתנה במחברת: 
 <a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/d/d3cc6d09ae4773b4c44ff52a4e4a99f9e883ab76.png" data-download-href="https://forums.pythonic.guru/uploads/default/d3cc6d09ae4773b4c44ff52a4e4a99f9e883ab76" title="a">[a]</a> 
מה הגישה לגבי הערה זו? האם מותר לנו לבצע פקודת return בבלוק ה-finally כבדוגמה?
  </blockquote>
</aside>
<p></p>
          <p><a href="https://forums.pythonic.guru/t/topic/7648/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/7648/2</link>
        <pubDate>Sun, 26 Jul 2020 10:48:42 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-7648-2</guid>
        <source url="https://forums.pythonic.guru/t/topic/7648.rss">פותחים שעון - פינלי</source>
      </item>
      <item>
        <title>פותחים שעון - פינלי</title>
        <dc:creator><![CDATA[Ellen]]></dc:creator>
        <description><![CDATA[
            <p>היוש, שמתי return  בתוך הכשלבסוף בדיוק כמו בדוגמה שלפניו וקיבלתי את השגיאה הבאה מהבודק:</p>
<pre><code>הבודק האוטומטי: B012-return/continue/break inside finally blocks cause exceptions to be silenced. Exceptions should be silenced in except blocks. Control statements can be moved outside the finally bloc
</code></pre>
<p>האם הותעתי ע"י התרגיל שלפניו?</p>
          <p><a href="https://forums.pythonic.guru/t/topic/7648/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/7648/1</link>
        <pubDate>Sun, 26 Jul 2020 10:11:41 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-7648-1</guid>
        <source url="https://forums.pythonic.guru/t/topic/7648.rss">פותחים שעון - פינלי</source>
      </item>
  </channel>
</rss>
